import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

const neutral = {
    light: {
        primary: "#2f6fff",
        primaryHover: "#5b8cff",
        primaryText: "#ffffff",
        menuBg: "#edf5ff",
        menuText: "#101a35",
        selectActiveBg: "#f1f6ff",
        selectSelectedBg: "rgba(47, 111, 255, 0.12)",
        selectText: "#1e4db7",
        selectBorder: "#b8c9ee",
        selectOutline: "rgba(47, 111, 255, 0.16)",
        selectShadow: "0 14px 32px rgba(30, 61, 126, 0.14), 0 3px 10px rgba(30, 61, 126, 0.06)",
        tableSelectedBg: "rgba(47, 111, 255, 0.1)",
        tableSelectedHoverBg: "rgba(47, 111, 255, 0.16)",
        layoutBg: "#f5f8ff",
        containerBg: "#ffffff",
        border: "#dfe7f3",
        text: "#13203b",
        textSecondary: "#687894",
    },
    dark: {
        primary: "#70d9ff",
        primaryHover: "#99e5ff",
        primaryText: "#04142b",
        menuBg: "#102445",
        menuText: "#f5f9ff",
        selectActiveBg: "#172d52",
        selectSelectedBg: "rgba(112, 217, 255, 0.18)",
        selectText: "#c8f4ff",
        selectBorder: "#38577f",
        selectOutline: "rgba(112, 217, 255, 0.2)",
        selectShadow: "0 16px 36px rgba(0, 0, 0, 0.36), 0 3px 10px rgba(0, 0, 0, 0.22)",
        tableSelectedBg: "rgba(112, 217, 255, 0.16)",
        tableSelectedHoverBg: "rgba(112, 217, 255, 0.24)",
        layoutBg: "#071224",
        containerBg: "#0d1b33",
        border: "#213b60",
        text: "#eef6ff",
        textSecondary: "#9fb2cd",
    },
};

export function getAntThemeConfig(dark: boolean): ThemeConfig {
    const color = dark ? neutral.dark : neutral.light;

    return {
        algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        cssVar: { key: dark ? "dreamyo-dark" : "dreamyo-light" },
        token: {
            colorPrimary: color.primary,
            colorInfo: color.primary,
            colorLink: color.primary,
            colorLinkHover: color.primaryHover,
            colorLinkActive: color.primary,
            colorTextLightSolid: color.primaryText,
            colorBgLayout: color.layoutBg,
            colorBgContainer: color.containerBg,
            colorBorder: color.border,
            colorText: color.text,
            colorTextSecondary: color.textSecondary,
            borderRadius: 8,
        },
        components: {
            Button: {
                primaryShadow: "none",
            },
            Segmented: {
                itemSelectedBg: color.selectSelectedBg,
                itemSelectedColor: color.selectText,
                itemHoverBg: color.selectActiveBg,
                trackBg: dark ? "rgba(255, 255, 255, 0.045)" : "rgba(91, 111, 139, 0.1)",
            },
            Slider: {
                handleActiveColor: dark ? "#70d9ff" : "#2f6fff",
                handleActiveOutlineColor: dark ? "rgba(112, 217, 255, 0.2)" : "rgba(47, 111, 255, 0.16)",
                handleColor: dark ? "#70d9ff" : "#2f6fff",
                trackBg: dark ? "#42bfe8" : "#2f6fff",
                trackHoverBg: dark ? "#70d9ff" : "#5b8cff",
            },
            Switch: {
                handleBg: "#ffffff",
            },
            Tabs: {
                inkBarColor: dark ? "#70d9ff" : "#2f6fff",
                itemActiveColor: color.selectText,
                itemHoverColor: dark ? "#d9f8ff" : "#1e4db7",
                itemSelectedColor: color.selectText,
            },
            Radio: {
                buttonCheckedBg: color.selectSelectedBg,
                buttonCheckedColorDisabled: color.textSecondary,
                buttonSolidCheckedBg: dark ? "#42bfe8" : "#2f6fff",
                buttonSolidCheckedHoverBg: dark ? "#70d9ff" : "#5b8cff",
                buttonSolidCheckedActiveBg: dark ? "#299fc8" : "#245bd0",
            },
            Menu: {
                itemActiveBg: color.menuBg,
                itemHoverBg: color.menuBg,
                itemSelectedBg: color.selectSelectedBg,
                itemSelectedColor: color.selectText,
                darkItemHoverBg: neutral.dark.menuBg,
                darkItemSelectedBg: neutral.dark.selectSelectedBg,
                darkItemSelectedColor: neutral.dark.selectText,
            },
            Select: {
                activeBorderColor: color.selectBorder,
                activeOutlineColor: color.selectOutline,
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgActiveHover: color.selectSelectedBg,
                hoverBorderColor: color.selectBorder,
                optionActiveBg: color.selectActiveBg,
                optionHeight: 32,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            Cascader: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgHover: color.selectActiveBg,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            TreeSelect: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                nodeHoverBg: color.selectActiveBg,
                nodeHoverColor: color.selectText,
                nodeSelectedBg: color.selectSelectedBg,
                nodeSelectedColor: color.selectText,
            },
            Table: {
                rowSelectedBg: color.tableSelectedBg,
                rowSelectedHoverBg: color.tableSelectedHoverBg,
            },
        },
    };
}
