import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

const neutral = {
    light: {
        primary: "#5b5ce2",
        primaryHover: "#696eff",
        primaryText: "#ffffff",
        menuBg: "#f5f5f5",
        menuText: "#171717",
        selectActiveBg: "#f4f5f7",
        selectSelectedBg: "rgba(42, 193, 215, 0.12)",
        selectText: "#194d67",
        selectBorder: "#c9ced5",
        selectOutline: "rgba(32, 36, 42, 0.08)",
        selectShadow: "0 8px 24px rgba(15, 23, 42, 0.08), 0 2px 6px rgba(15, 23, 42, 0.04)",
        tableSelectedBg: "rgba(42, 193, 215, 0.1)",
        tableSelectedHoverBg: "rgba(42, 193, 215, 0.15)",
        layoutBg: "#fafbfc",
        containerBg: "#ffffff",
        border: "#e5e8ec",
        text: "#20242a",
        textSecondary: "#697381",
    },
    dark: {
        primary: "#7277ff",
        primaryHover: "#8589ff",
        primaryText: "#ffffff",
        menuBg: "#262626",
        menuText: "#fafafa",
        selectActiveBg: "#262b31",
        selectSelectedBg: "rgba(30, 92, 112, 0.58)",
        selectText: "#f2fbff",
        selectBorder: "#464c55",
        selectOutline: "rgba(255, 255, 255, 0.08)",
        selectShadow: "0 12px 28px rgba(0, 0, 0, 0.28), 0 2px 8px rgba(0, 0, 0, 0.18)",
        tableSelectedBg: "rgba(30, 92, 112, 0.42)",
        tableSelectedHoverBg: "rgba(36, 111, 132, 0.5)",
        layoutBg: "#111316",
        containerBg: "#181b20",
        border: "#2b3037",
        text: "#f3f5f7",
        textSecondary: "#9aa3af",
    },
};

export function getAntThemeConfig(dark: boolean): ThemeConfig {
    const color = dark ? neutral.dark : neutral.light;

    return {
        algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        cssVar: { key: dark ? "octaflow-dark" : "octaflow-light" },
        token: {
            colorPrimary: color.primary,
            colorInfo: color.primary,
            colorLink: color.primary,
            colorLinkHover: color.primaryHover,
            colorLinkActive: color.primary,
            colorTextLightSolid: color.primaryText,
            colorBgLayout: color.layoutBg,
            colorBgContainer: color.containerBg,
            colorBorder: color.border,
            colorText: color.text,
            colorTextSecondary: color.textSecondary,
            borderRadius: 8,
        },
        components: {
            Button: {
                primaryShadow: "none",
            },
            Segmented: {
                itemSelectedBg: color.selectSelectedBg,
                itemSelectedColor: color.selectText,
                itemHoverBg: color.selectActiveBg,
                trackBg: dark ? "rgba(255, 255, 255, 0.045)" : "rgba(91, 111, 139, 0.1)",
            },
            Slider: {
                handleActiveColor: dark ? "#67e2f2" : "#1c9fba",
                handleActiveOutlineColor: dark ? "rgba(103, 226, 242, 0.2)" : "rgba(28, 159, 186, 0.16)",
                handleColor: dark ? "#67e2f2" : "#1c9fba",
                trackBg: dark ? "#49cfe2" : "#279fba",
                trackHoverBg: dark ? "#67e2f2" : "#1c8ba3",
            },
            Switch: {
                handleBg: "#ffffff",
            },
            Tabs: {
                inkBarColor: dark ? "#67e2f2" : "#1c9fba",
                itemActiveColor: color.selectText,
                itemHoverColor: dark ? "#c7f8ff" : "#17627a",
                itemSelectedColor: color.selectText,
            },
            Radio: {
                buttonCheckedBg: color.selectSelectedBg,
                buttonCheckedColorDisabled: color.textSecondary,
                buttonSolidCheckedBg: dark ? "#36b8ce" : "#208fa8",
                buttonSolidCheckedHoverBg: dark ? "#4bcee1" : "#197d94",
                buttonSolidCheckedActiveBg: dark ? "#2ca2b8" : "#176e82",
            },
            Menu: {
                itemActiveBg: color.menuBg,
                itemHoverBg: color.menuBg,
                itemSelectedBg: color.selectSelectedBg,
                itemSelectedColor: color.selectText,
                darkItemHoverBg: neutral.dark.menuBg,
                darkItemSelectedBg: neutral.dark.selectSelectedBg,
                darkItemSelectedColor: neutral.dark.selectText,
            },
            Select: {
                activeBorderColor: color.selectBorder,
                activeOutlineColor: color.selectOutline,
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgActiveHover: color.selectSelectedBg,
                hoverBorderColor: color.selectBorder,
                optionActiveBg: color.selectActiveBg,
                optionHeight: 32,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            Cascader: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgHover: color.selectActiveBg,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            TreeSelect: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                nodeHoverBg: color.selectActiveBg,
                nodeHoverColor: color.selectText,
                nodeSelectedBg: color.selectSelectedBg,
                nodeSelectedColor: color.selectText,
            },
            Table: {
                rowSelectedBg: color.tableSelectedBg,
                rowSelectedHoverBg: color.tableSelectedHoverBg,
            },
        },
    };
}
