import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

const neutral = {
    light: {
        primary: "#5e7ff1",
        primaryHover: "#35cce1",
        primaryText: "#ffffff",
        menuBg: "#edf5ff",
        menuText: "#13213f",
        selectActiveBg: "#edf8fb",
        selectSelectedBg: "rgba(94, 127, 241, 0.14)",
        selectText: "#3856b2",
        selectBorder: "#b7c8f5",
        selectOutline: "rgba(94, 127, 241, 0.18)",
        selectShadow: "0 14px 32px rgba(30, 61, 126, 0.14), 0 3px 10px rgba(30, 61, 126, 0.06)",
        tableSelectedBg: "rgba(94, 127, 241, 0.1)",
        tableSelectedHoverBg: "rgba(94, 127, 241, 0.16)",
        layoutBg: "#f4f8ff",
        containerBg: "#ffffff",
        border: "#d5e3f3",
        text: "#13213f",
        textSecondary: "#637394",
    },
    dark: {
        primary: "#35cce1",
        primaryHover: "#58dec9",
        primaryText: "#071224",
        menuBg: "#142953",
        menuText: "#f5f9ff",
        selectActiveBg: "#1a3567",
        selectSelectedBg: "rgba(53, 204, 225, 0.2)",
        selectText: "#c7f4ff",
        selectBorder: "#4f75ad",
        selectOutline: "rgba(53, 204, 225, 0.24)",
        selectShadow: "0 16px 36px rgba(0, 0, 0, 0.36), 0 3px 10px rgba(0, 0, 0, 0.22)",
        tableSelectedBg: "rgba(53, 204, 225, 0.16)",
        tableSelectedHoverBg: "rgba(53, 204, 225, 0.24)",
        layoutBg: "#080f20",
        containerBg: "#0e1c3a",
        border: "#263d68",
        text: "#eef6ff",
        textSecondary: "#a8b6d2",
    },
};

export function getAntThemeConfig(dark: boolean): ThemeConfig {
    const color = dark ? neutral.dark : neutral.light;

    return {
        algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        cssVar: { key: dark ? "dreamyo-dark" : "dreamyo-light" },
        token: {
            colorPrimary: color.primary,
            colorInfo: color.primary,
            colorLink: color.primary,
            colorLinkHover: color.primaryHover,
            colorLinkActive: color.primary,
            colorTextLightSolid: color.primaryText,
            colorBgLayout: color.layoutBg,
            colorBgContainer: color.containerBg,
            colorBorder: color.border,
            colorText: color.text,
            colorTextSecondary: color.textSecondary,
            borderRadius: 8,
        },
        components: {
            Button: {
                primaryShadow: "none",
            },
            Segmented: {
                itemSelectedBg: color.selectSelectedBg,
                itemSelectedColor: color.selectText,
                itemHoverBg: color.selectActiveBg,
                trackBg: dark ? "rgba(255, 255, 255, 0.045)" : "rgba(91, 111, 139, 0.1)",
            },
            Slider: {
                handleActiveColor: dark ? "#35cce1" : "#5e7ff1",
                handleActiveOutlineColor: dark ? "rgba(53, 204, 225, 0.22)" : "rgba(94, 127, 241, 0.18)",
                handleColor: dark ? "#35cce1" : "#5e7ff1",
                trackBg: dark ? "#24b9d2" : "#5e7ff1",
                trackHoverBg: dark ? "#58dec9" : "#35cce1",
            },
            Switch: {
                handleBg: "#ffffff",
            },
            Tabs: {
                inkBarColor: dark ? "#35cce1" : "#5e7ff1",
                itemActiveColor: color.selectText,
                itemHoverColor: dark ? "#d9f8ff" : "#1e4db7",
                itemSelectedColor: color.selectText,
            },
            Radio: {
                buttonCheckedBg: color.selectSelectedBg,
                buttonCheckedColorDisabled: color.textSecondary,
                buttonSolidCheckedBg: dark ? "#24b9d2" : "#5e7ff1",
                buttonSolidCheckedHoverBg: dark ? "#58dec9" : "#35cce1",
                buttonSolidCheckedActiveBg: dark ? "#188da4" : "#4565d0",
            },
            Menu: {
                itemActiveBg: color.menuBg,
                itemHoverBg: color.menuBg,
                itemSelectedBg: color.selectSelectedBg,
                itemSelectedColor: color.selectText,
                darkItemHoverBg: neutral.dark.menuBg,
                darkItemSelectedBg: neutral.dark.selectSelectedBg,
                darkItemSelectedColor: neutral.dark.selectText,
            },
            Select: {
                activeBorderColor: color.selectBorder,
                activeOutlineColor: color.selectOutline,
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgActiveHover: color.selectSelectedBg,
                hoverBorderColor: color.selectBorder,
                optionActiveBg: color.selectActiveBg,
                optionHeight: 32,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            Cascader: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgHover: color.selectActiveBg,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            TreeSelect: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                nodeHoverBg: color.selectActiveBg,
                nodeHoverColor: color.selectText,
                nodeSelectedBg: color.selectSelectedBg,
                nodeSelectedColor: color.selectText,
            },
            Table: {
                rowSelectedBg: color.tableSelectedBg,
                rowSelectedHoverBg: color.tableSelectedHoverBg,
            },
        },
    };
}
