import { expect, test } from "@playwright/test";

const cards = Array.from({ length: 9 }, (_, index) => ({
    id: `image-workbench:visual-${index}`,
    kind: "image",
    status: index === 8 ? "pending" : "success",
    title: `测试图片 ${index + 1}`,
    prompt: `测试图片 ${index + 1}`,
    model: "e2e-image",
    assets: index === 8 ? [] : [{ type: "image", url: "/design/home/latest-gallery-1.webp", mimeType: "image/webp", width: 1200, height: 800 }],
    requestSnapshot: { version: 1, userPrompt: `测试图片 ${index + 1}`, parameters: { model: "e2e-image", size: "16:9" }, references: [], slots: [{ id: `slot-${index}`, index: 0, status: index === 8 ? "pending" : "success", assetIndex: index === 8 ? undefined : 0, startedAt: Date.now() - 12_000 }] },
    createdAt: "2026-09-24T04:00:00.000Z",
    durationMs: 12_000,
}));

test("unified generation page keeps nine cards, theme, parameter menus and reference picker usable", async ({ page }, testInfo) => {
    await page.route("**/api/generation-logs**", (route) => route.fulfill({ json: { items: new URL(route.request().url()).searchParams.get("kind") === "image" ? cards : [] } }));
    await page.route("**/api/library-assets**", (route) => route.fulfill({ json: { code: 0, data: { assets: [], total: 0, page: 1, pageSize: 100 }, msg: "OK" } }));
    await page.route("**/api/model-generation-stats", (route) => route.fulfill({ json: { data: { "e2e-image": { avgDurationMs: 30_000, samples: 3 } } } }));
    await page.route("**/api/runninghub/apps?binding=interior-design", (route) => route.fulfill({ json: { code: 0, data: [{ id: "interior-test", remoteId: "interior-test", kind: "workflow", name: "测试室内设计应用", description: "", thumbnailUrl: "", featureBindings: ["interior-design"], fieldCount: 0 }], msg: "OK" } }));
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto("/create?mode=image");
    const workbench = page.locator('[data-testid="image-video-workbench"]:visible').first();
    await expect(workbench).toBeVisible();
    const themeButton = page.getByRole("button", { name: /切换.*主题/ });
    if (await workbench.getAttribute("data-theme") === "dark") await themeButton.click();
    await expect(page.getByRole("button", { name: "图片", exact: true })).toHaveAttribute("aria-pressed", "true");
    await expect(page.getByRole("button", { name: "图片比例：16:9" })).toBeVisible();
    await expect(page.getByRole("button", { name: "画质：低 · 1K" })).toBeVisible();
    await expect(page.getByRole("button", { name: "生成数量：1" })).toBeVisible();
    const modelTrigger = workbench.locator(".canvas-composer-model-picker").first();
    await modelTrigger.click();
    const modelPanel = page.locator("[data-model-picker-panel]");
    await expect(modelPanel).toBeVisible();
    const triggerRect = await modelTrigger.boundingBox();
    const panelRect = await modelPanel.boundingBox();
    expect(panelRect!.x).toBeGreaterThanOrEqual(triggerRect!.x + triggerRect!.width - 2);
    await page.locator("#workbench-prompt").click();
    await expect(modelPanel).toBeHidden();
    await page.getByRole("button", { name: "图片比例：16:9" }).click();
    await page.getByRole("option", { name: "3:4" }).click();
    await expect(page.getByRole("button", { name: "图片比例：3:4" })).toBeVisible();
    await expect(page.getByRole("option", { name: "3:4" })).toHaveCount(0);
    await page.getByRole("button", { name: /添加参考图片/ }).click();
    const referenceDialog = page.getByRole("dialog", { name: "添加参考图片" });
    await expect(referenceDialog).toBeVisible();
    const sidebarRect = await workbench.locator("aside").boundingBox();
    const resultsRect = await workbench.getByRole("region", { name: "生成结果" }).boundingBox();
    await expect.poll(async () => (await referenceDialog.boundingBox())?.x).toBeCloseTo(resultsRect!.x, 0);
    const dialogRect = await referenceDialog.boundingBox();
    expect(dialogRect!.x).toBeCloseTo(resultsRect!.x, 0);
    expect(dialogRect!.y).toBeCloseTo(sidebarRect!.y, 0);
    expect(dialogRect!.width).toBeLessThanOrEqual(600);
    expect(dialogRect!.height).toBeLessThan(sidebarRect!.height);
    await page.getByRole("button", { name: "本机上传" }).click();
    await expect(page.getByText("拖拽、粘贴或选择图片")).toBeVisible();
    await page.getByRole("dialog", { name: "添加参考图片" }).getByRole("button", { name: "Close" }).click();
    await expect(page.getByRole("dialog", { name: "添加参考图片" })).toBeHidden();
    await page.getByRole("button", { name: /室内设计 SU 直出/ }).click();
    const interiorDialog = page.getByRole("dialog", { name: "室内设计" });
    await expect(interiorDialog).toBeVisible();
    await expect.poll(async () => (await interiorDialog.boundingBox())?.x).toBeCloseTo(dialogRect!.x, 0);
    const interiorRect = await interiorDialog.boundingBox();
    expect(interiorRect!.x).toBeCloseTo(dialogRect!.x, 0);
    expect(interiorRect!.y).toBeCloseTo(dialogRect!.y, 0);
    expect(interiorRect!.width).toBeCloseTo(780, 0);
    expect(interiorRect!.width / dialogRect!.width).toBeCloseTo(1.3, 1);
    await expect(interiorDialog.locator(".ant-modal-title svg")).toHaveCount(1);
    await expect(interiorDialog.getByRole("button", { name: "SU直出摄影级照片" })).toBeVisible();
    await expect.poll(async () => interiorDialog.evaluate((element) => getComputedStyle(element).opacity)).toBe("1");
    await page.screenshot({ path: testInfo.outputPath("interior-catalog-light-1440.png") });
    await interiorDialog.getByRole("button", { name: "SU直出摄影级照片" }).click();
    await expect(interiorDialog.getByText("配置参数后，使用左侧")).toHaveCount(0);
    await expect(interiorDialog.getByRole("button", { name: /生图模式/ })).toHaveAttribute("aria-expanded", "true");
    await interiorDialog.getByRole("radiogroup", { name: "转换逻辑" }).getByRole("radio", { name: "写实效果图" }).click();
    await interiorDialog.getByRole("button", { name: /场景设计/ }).click();
    await interiorDialog.getByRole("radiogroup", { name: "空间类型" }).getByRole("radio", { name: "办公" }).click();
    await interiorDialog.getByRole("button", { name: /光影氛围/ }).click();
    const season = interiorDialog.getByRole("radiogroup", { name: "季节" });
    const weather = interiorDialog.getByRole("radiogroup", { name: "天气" });
    const time = interiorDialog.getByRole("radiogroup", { name: "时间段" });
    await expect(season).toBeVisible();
    await expect(weather).toBeVisible();
    await expect(time).toBeVisible();
    await season.getByRole("radio", { name: "秋季" }).click();
    await weather.getByRole("radio", { name: "雨天" }).click();
    await time.getByRole("radio", { name: "下午16点" }).click();
    await expect(season.getByRole("radio", { name: "秋季" })).toHaveAttribute("aria-checked", "true");
    expect(await season.getByRole("radio", { name: "秋季" }).evaluate((element) => getComputedStyle(element).backgroundImage)).not.toBe("none");
    await expect(weather.getByRole("radio", { name: "雨天" })).toHaveAttribute("aria-checked", "true");
    await expect(time.getByRole("radio", { name: "下午16点" })).toHaveAttribute("aria-checked", "true");
    await page.screenshot({ path: testInfo.outputPath("interior-settings-light-1440.png") });
    await interiorDialog.getByRole("button", { name: /摄影设备/ }).click();
    await expect(interiorDialog.getByLabel("相机")).toBeVisible();
    await interiorDialog.getByRole("radiogroup", { name: "光圈" }).getByRole("radio", { name: "f/8" }).click();
    await interiorDialog.getByRole("group", { name: "摄影技法" }).getByRole("button", { name: "HDR包围曝光" }).click();
    await expect(interiorDialog.getByRole("group", { name: "摄影技法" }).getByRole("button", { name: "HDR包围曝光" })).toHaveAttribute("aria-pressed", "true");
    await interiorDialog.getByRole("button", { name: /AI 约束/ }).click();
    await interiorDialog.getByRole("radiogroup", { name: "几何保真" }).getByRole("radio", { name: "硬装不动" }).click();
    await interiorDialog.getByRole("button", { name: "返回功能列表" }).click();
    await expect(interiorDialog.getByRole("button", { name: "SU直出摄影级照片" })).toBeVisible();
    await interiorDialog.getByRole("button", { name: "测试室内设计应用" }).click();
    await interiorDialog.getByRole("button", { name: "使用此配置" }).click();
    await expect(interiorDialog).toBeHidden();
    await page.getByRole("button", { name: "图片比例：3:4" }).click();
    await page.getByRole("option", { name: "1:1" }).click();
    await page.getByRole("button", { name: "画质：低 · 1K" }).click();
    await page.getByRole("option", { name: "中 · 2K" }).click();
    await page.getByRole("button", { name: "生成数量：1" }).click();
    await page.getByRole("button", { name: "增加数量" }).click();
    await expect(page.getByRole("button", { name: "图片比例：1:1" })).toBeVisible();
    await expect(page.getByRole("button", { name: "画质：中 · 2K" })).toBeVisible();
    await expect(page.getByRole("button", { name: "生成数量：2" })).toBeVisible();
    const interiorEntry = workbench.getByRole("button", { name: /测试室内设计应用/ });
    const interiorClear = workbench.getByRole("button", { name: "移除室内设计配置" });
    await expect.poll(async () => (await interiorEntry.boundingBox())?.height).toBeCloseTo((await interiorClear.boundingBox())!.height, 0);
    await page.screenshot({ path: testInfo.outputPath("interior-selected-parameters-light-1440.png") });
    await interiorClear.click();
    const resultCards = workbench.locator("article");
    await expect(resultCards).toHaveCount(9);
    const geometry = await resultCards.evaluateAll((items) => items.map((item) => { const rect = item.getBoundingClientRect(); return { top: rect.top, left: rect.left, bottom: rect.bottom }; }));
    expect(geometry[0].top).toBeCloseTo(geometry[1].top, 0);
    expect(geometry[0].top).toBeCloseTo(geometry[2].top, 0);
    expect(geometry[3].top).toBeGreaterThan(geometry[0].top);
    expect(geometry[6].top).toBeGreaterThan(geometry[3].top);
    expect(geometry[8].bottom).toBeLessThanOrEqual(900);
    await expect(resultCards.last()).toContainText("已等待");
    await page.screenshot({ path: testInfo.outputPath("generation-light-1440.png") });
    const previewButton = resultCards.first().getByRole("button", { name: "查看大图" });
    await resultCards.first().hover();
    await expect(previewButton.locator("svg")).toHaveClass(/lucide-zoom-in/);
    await previewButton.hover();
    await expect.poll(() => previewButton.evaluate((element) => getComputedStyle(element, "::after").opacity), { timeout: 500 }).toBe("1");
    await previewButton.click();
    const lightbox = page.locator(".ant-modal:visible").last();
    await expect.poll(() => lightbox.evaluate((element) => getComputedStyle(element).opacity)).toBe("1");
    await expect(lightbox.getByRole("button", { name: "下载原图" })).toBeVisible();
    await expect(lightbox.getByRole("button", { name: "关闭预览" })).toBeVisible();
    await expect.poll(async () => (await lightbox.locator("img").boundingBox())?.width).toBeGreaterThan(800);
    expect(await lightbox.locator(".ant-modal-container").evaluate((element) => getComputedStyle(element).backgroundColor)).toBe("rgba(0, 0, 0, 0)");
    expect(await lightbox.locator(".ant-modal-container").evaluate((element) => getComputedStyle(element).paddingLeft)).toBe("0px");
    await page.screenshot({ path: testInfo.outputPath("image-preview-light-1440.png") });
    await lightbox.getByRole("button", { name: "关闭预览" }).click();
    await page.setViewportSize({ width: 2059, height: 940 });
    const wideGeometry = await resultCards.evaluateAll((items) => items.map((item) => {
        const card = item.getBoundingClientRect();
        const media = item.querySelector("[class*='mediaFrame']")?.getBoundingClientRect();
        return { top: card.top, left: card.left, cardWidth: card.width, mediaWidth: media?.width || 0, mediaHeight: media?.height || 0 };
    }));
    expect(wideGeometry.slice(0, 4).every((item) => Math.abs(item.top - wideGeometry[0].top) < 1)).toBe(true);
    expect(wideGeometry[4].top).toBeGreaterThan(wideGeometry[0].top);
    expect(wideGeometry[3].left).toBeGreaterThan(wideGeometry[2].left);
    expect(wideGeometry[0].mediaWidth / wideGeometry[0].mediaHeight).toBeCloseTo(1.9, 1);
    await page.screenshot({ path: testInfo.outputPath("generation-light-2059.png") });
    await page.setViewportSize({ width: 1440, height: 900 });
    await themeButton.click();
    await expect(workbench).toHaveAttribute("data-theme", "dark");
    await page.screenshot({ path: testInfo.outputPath("generation-dark-1440.png") });
    await page.getByRole("button", { name: "视频", exact: true }).click();
    await expect(page).toHaveURL(/\/create\?mode=video/);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(workbench).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
    await page.getByRole("button", { name: /添加参考图片/ }).click();
    const mobileDialog = await page.getByRole("dialog", { name: "添加参考图片" }).boundingBox();
    expect(mobileDialog!.x).toBeGreaterThanOrEqual(0);
    expect(mobileDialog!.x + mobileDialog!.width).toBeLessThanOrEqual(390);
    expect(mobileDialog!.y + mobileDialog!.height).toBeLessThanOrEqual(844);
    await page.screenshot({ path: testInfo.outputPath("generation-mobile-390.png") });
    await page.getByRole("dialog", { name: "添加参考图片" }).getByRole("button", { name: "Close" }).click();
    await page.getByRole("button", { name: "图片", exact: true }).click();
    await page.getByRole("button", { name: /室内设计 SU 直出/ }).click();
    const mobileInterior = page.getByRole("dialog", { name: "室内设计" });
    await expect.poll(async () => mobileInterior.evaluate((element) => getComputedStyle(element).opacity)).toBe("1");
    const mobileInteriorRect = await mobileInterior.boundingBox();
    expect(mobileInteriorRect!.x).toBeGreaterThanOrEqual(0);
    expect(mobileInteriorRect!.x + mobileInteriorRect!.width).toBeLessThanOrEqual(390);
    await mobileInterior.getByRole("button", { name: "SU直出摄影级照片" }).click();
    await mobileInterior.getByRole("button", { name: /光影氛围/ }).click();
    await expect(mobileInterior.getByRole("radiogroup", { name: "天气" }).getByRole("radio", { name: "晴天" })).toBeVisible();
    expect(await mobileInterior.evaluate((element) => element.scrollWidth)).toBeLessThanOrEqual(mobileInteriorRect!.width + 1);
    await page.screenshot({ path: testInfo.outputPath("interior-settings-dark-390.png") });
    await page.setViewportSize({ width: 430, height: 932 });
    const tabletInteriorRect = await mobileInterior.boundingBox();
    expect(tabletInteriorRect!.x).toBeGreaterThanOrEqual(0);
    expect(tabletInteriorRect!.x + tabletInteriorRect!.width).toBeLessThanOrEqual(430);
    await mobileInterior.getByRole("button", { name: "Close" }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await resultCards.first().getByRole("button", { name: "查看大图" }).click();
    const mobileLightbox = page.locator(".ant-modal:visible").last();
    await expect.poll(() => mobileLightbox.evaluate((element) => getComputedStyle(element).opacity)).toBe("1");
    const mobileImage = await mobileLightbox.locator("img").boundingBox();
    expect(mobileImage!.x).toBeGreaterThanOrEqual(0);
    expect(mobileImage!.x + mobileImage!.width).toBeLessThanOrEqual(390);
    await expect(mobileLightbox.getByRole("button", { name: "关闭预览" })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("image-preview-dark-390.png") });
});
